#pragma warning disable ASPIREDOCKERFILEBUILDER001

using Aspire.Hosting.ApplicationModel;
using Aspire.Hosting.ApplicationModel.Docker;

namespace Aspire.Hosting.PHP;

/// <summary>
/// Writes the Dockerfiles this integration generates.
/// </summary>
/// <remarks>
/// <para>
/// PHP images are single stage, unlike the Rust and Python ones. There is nothing to compile away: the source
/// that runs is the source that shipped, and the base images already contain Composer, so a separate runtime
/// stage would be byte-identical to the build stage. Layer caching is still handled properly by copying
/// <c>composer.json</c> ahead of the rest of the source.
/// </para>
/// <para>
/// Two shapes are produced. <see cref="WritePublishDockerfile"/> builds the deployable image with the source
/// baked in. <see cref="WriteDevDockerfile"/> builds only the environment — extensions and ini settings — for
/// run mode, where the source arrives through a bind mount instead.
/// </para>
/// </remarks>
internal static class PhpDockerfileGenerator
{
    private const string ComposerCacheMount = "type=cache,target=/tmp/composer-cache";

    /// <summary>
    /// Files excluded from the build context when the application has no <c>.dockerignore</c> of its own.
    /// </summary>
    /// <remarks>
    /// <c>vendor</c> matters most: it is routinely hundreds of megabytes, it is rebuilt inside the image anyway,
    /// and a host <c>vendor</c> built on Windows or macOS can carry platform-specific paths into a Linux image.
    /// </remarks>
    public const string DefaultBuildContextIgnoreContent = """
        # Generated by Aspire.Hosting.PHP. Author <contextRoot>/.dockerignore to take over these rules.
        vendor
        node_modules
        .git
        .gitignore
        .env
        .env.*
        .aspire
        aspire-output
        .DS_Store
        Dockerfile
        Dockerfile.*
        .dockerignore

        """;

    /// <summary>
    /// Writes the image that runs the application, with the source baked in.
    /// </summary>
    public static void WritePublishDockerfile(IPhpResource resource, DockerfileBuilderCallbackContext context)
    {
        var options = PhpDockerfileOptions.Resolve(resource, context.Resource);

        var stage = context.Builder.From(options.Image);

        WriteEnvironmentSetup(stage, options, resource.Name);

        stage
            .WorkDir(PhpImages.AppBaseDirectory)
            .EmptyLine();

        WriteComposerInstall(stage, options);

        stage
            .Comment("Application source")
            .Copy(".", ".", Chown)
            .EmptyLine();

        if (options.UsesComposer)
        {
            // Deferred until the full source is present: the autoloader classmap has to see every class, and
            // scripts such as post-install-cmd routinely touch files that only exist in the complete tree.
            // classmap-authoritative goes further than optimize: the autoloader never falls back to searching
            // the filesystem, so a class miss is an error rather than a slow lookup. Correct for a fixed image.
            var autoloaderFlag = options.ClassmapAuthoritative ? "--classmap-authoritative" : "--optimize";

            stage
                .Comment("Build the optimized autoloader now the whole source tree is present")
                .RunWithMounts($"composer dump-autoload {autoloaderFlag} --no-dev --no-interaction", ComposerCacheMount)
                .EmptyLine();
        }

        WritePreloadSettings(stage, options, resource.Name);

        if (options.IsWeb)
        {
            // No ENTRYPOINT: the base image starts FrankenPHP itself. The listening port and document root are
            // supplied as resource environment variables so Aspire can resolve the port it allocated.
            stage
                .Comment("FrankenPHP serves the application; the port and document root arrive as environment variables")
                .Expose(PhpImages.DefaultWebContainerPort);
        }
        else
        {
            stage.Entrypoint(["php", options.ScriptPath ?? throw new DistributedApplicationException(
                $"The PHP app '{resource.Name}' has no script to run. This is a bug in Aspire.Hosting.PHP.")]);
        }
    }

    /// <summary>
    /// Writes the run-mode image: the PHP environment only, with no application source.
    /// </summary>
    /// <remarks>
    /// The source is bind-mounted at run time instead of copied, so edits take effect without a rebuild and
    /// <c>vendor/</c> is written back to the host where editors and static analysis can see it.
    /// </remarks>
    public static void WriteDevDockerfile(IPhpResource resource, DockerfileBuilderCallbackContext context)
    {
        var options = PhpDockerfileOptions.Resolve(resource, context.Resource);

        var stage = context.Builder.From(options.Image);

        stage
            .Comment("Run-mode image: environment only. The application is bind-mounted at " + PhpImages.AppBaseDirectory + ".")
            .EmptyLine();

        WriteEnvironmentSetup(stage, options, resource.Name);

        stage.WorkDir(PhpImages.AppBaseDirectory);
    }

    private static void WriteEnvironmentSetup(DockerfileStage stage, PhpDockerfileOptions options, string resourceName)
    {
        var needsRoot = options.Extensions.Count > 0
            || options.IniSettings.Count > 0
            || options.SystemPackages.Count > 0
            || options.WriteForwardedHeaderShim;

        if (!needsRoot)
        {
            return;
        }

        // install-php-extensions and writing into conf.d both need root; the images otherwise run unprivileged.
        stage.User("root");

        if (options.SystemPackages.Count > 0)
        {
            foreach (var package in options.SystemPackages)
            {
                ValidateShellToken(package, "system package name", resourceName);
            }

            var packages = string.Join(" ", options.SystemPackages);

            // The base image is overridable and the Apache variant is Debian, so neither package manager can
            // be assumed. Whichever exists is used.
            stage
                .Comment("System packages")
                .Run(
                    $"if command -v apk > /dev/null; then apk add --no-cache {packages}; " +
                    $"else apt-get update && apt-get install -y --no-install-recommends {packages} " +
                    "&& rm -rf /var/lib/apt/lists/*; fi")
                .EmptyLine();
        }

        if (options.Extensions.Count > 0)
        {
            foreach (var extension in options.Extensions)
            {
                ValidateShellToken(extension, "PHP extension name", resourceName);
            }

            // igbinary is installed on its own and first, because the Redis rebuild below only picks up
            // igbinary support if igbinary is already present when Redis is built.
            var ordered = options.RebuildRedisForIgbinary
                ? options.Extensions.Where(e => !string.Equals(e, "igbinary", StringComparison.Ordinal))
                : options.Extensions;

            if (options.RebuildRedisForIgbinary)
            {
                stage
                    .Comment("igbinary first: Redis only gains igbinary support if it is built against it")
                    .Run("install-php-extensions igbinary");
            }

            var remaining = ordered.ToList();
            if (remaining.Count > 0)
            {
                stage
                    .Comment("PHP extensions")
                    .Run($"install-php-extensions {string.Join(" ", remaining)}");
            }

            if (options.RebuildRedisForIgbinary)
            {
                // The base image already ships Redis built without igbinary, and the installer refuses to
                // replace an extension that is already present. Removing it first is the only way to get a
                // build that links against igbinary.
                stage
                    .Comment("Rebuild Redis against igbinary")
                    .Run(
                        "pecl uninstall -r redis && " +
                        $"rm -f {PhpImages.PhpConfDirectory}/docker-php-ext-redis.ini && " +
                        "install-php-extensions redis");
            }

            stage.EmptyLine();
        }

        if (options.WriteForwardedHeaderShim)
        {
            WriteForwardedHeaderShim(stage);
        }

        // Preload is deliberately excluded here and written at the very end instead. It names a file that
        // Composer has not created yet, and PHP fails to start at all when opcache.preload points at a
        // missing file — which would break the composer install a few lines below.
        var startupSettings = options.IniSettings
            .Where(setting => !IsPreloadSetting(setting.Key))
            .ToList();

        if (options.WriteForwardedHeaderShim)
        {
            startupSettings.Add(new KeyValuePair<string, string>(
                "auto_prepend_file",
                PhpHostingExtensions.ForwardedHeaderShimPath));
        }

        if (startupSettings.Count > 0)
        {
            WriteIniSettings(
                stage,
                startupSettings,
                resourceName,
                append: false,
                "php.ini settings. The four z prefix sorts after the base image's own ini files.");
        }

        stage
            .User(PhpImages.ContainerUser)
            .EmptyLine();
    }

    /// <summary>
    /// Writes the <c>$_SERVER</c> shim and points <c>auto_prepend_file</c> at it.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Base64 rather than a heredoc or a printf: the content is PHP, so it is full of quotes, dollar signs
    /// and brackets that every shell treats as special. Encoding it removes the question entirely, and
    /// <c>base64 -d</c> is present on both Alpine's busybox and Debian's coreutils.
    /// </para>
    /// <para>
    /// Written before the ini settings so the file already exists by the time PHP is next invoked. PHP warns
    /// on every invocation when <c>auto_prepend_file</c> names a missing file, which would otherwise litter
    /// the Composer output later in the build.
    /// </para>
    /// </remarks>
    private static void WriteForwardedHeaderShim(DockerfileStage stage)
    {
        var encoded = Convert.ToBase64String(
            System.Text.Encoding.UTF8.GetBytes(PhpHostingExtensions.ForwardedHeaderShimContent));

        stage
            .Comment("Populate $_SERVER from the forwarded headers: the platform terminates TLS at its ingress")
            .Run($"echo '{encoded}' | base64 -d > {PhpHostingExtensions.ForwardedHeaderShimPath}")
            .EmptyLine();
    }

    // opcache.preload names a file that only exists once the application and its dependencies are in place.
    private static bool IsPreloadSetting(string key)
        => key.StartsWith("opcache.preload", StringComparison.Ordinal);

    /// <summary>
    /// Appends the preload settings, once the file they name actually exists.
    /// </summary>
    /// <remarks>
    /// PHP refuses to start when <c>opcache.preload</c> points at a missing file, so writing this alongside
    /// the other settings would break every PHP invocation later in the build — Composer included.
    /// </remarks>
    private static void WritePreloadSettings(DockerfileStage stage, PhpDockerfileOptions options, string resourceName)
    {
        var preloadSettings = options.IniSettings
            .Where(setting => IsPreloadSetting(setting.Key))
            .ToList();

        if (preloadSettings.Count == 0)
        {
            return;
        }

        // Back to root briefly: the ini directory is not writable by the application user.
        stage.User("root");

        WriteIniSettings(
            stage,
            preloadSettings,
            resourceName,
            append: true,
            "Preloading, added last because it names a file Composer has only just created");

        stage
            .User(PhpImages.ContainerUser)
            .EmptyLine();
    }

    private static void WriteIniSettings(
        DockerfileStage stage,
        IReadOnlyCollection<KeyValuePair<string, string>> settings,
        string resourceName,
        bool append,
        string comment)
    {
        foreach (var setting in settings)
        {
            ValidateIniValue(setting.Key, "php.ini setting name", resourceName);
            ValidateIniValue(setting.Value, $"php.ini value for '{setting.Key}'", resourceName);
        }

        // printf with a %s per line rather than echo: echo's handling of backslashes and leading dashes
        // differs between shells, and these values come from the caller.
        var format = string.Join("", Enumerable.Repeat("%s\\n", settings.Count));
        var arguments = string.Join(
            " ",
            // The value is quoted in the ini file itself, not just shell-quoted. PHP's ini parser stops an
            // unquoted value at the next '=', which silently truncates anything containing one — a
            // sendmail_path of "msmtp --host=${MAIL_HOST} ..." arrives as "msmtp --host" and mail() fails
            // with no indication why. Quoting also keeps ${VAR} substitution working.
            settings.Select(setting => ShellQuote($"{setting.Key}=\"{EscapeIniValue(setting.Value)}\"")));

        var redirect = append ? ">>" : ">";

        stage
            .Comment(comment)
            .Run($"printf '{format}' {arguments} {redirect} {PhpImages.PhpConfDirectory}/{PhpImages.GeneratedIniFileName}")
            .EmptyLine();
    }

    private static void WriteComposerInstall(DockerfileStage stage, PhpDockerfileOptions options)
    {
        if (!options.UsesComposer)
        {
            return;
        }

        // Copied ahead of the source so a source-only edit does not invalidate the dependency layer.
        // composer.lock is matched by a glob rather than named, because COPY fails outright on a missing
        // file and an application without a committed lock file is legal.
        stage
            .Comment("Dependencies first, so editing source does not reinstall them")
            .Copy("composer.json composer.lock*", "./", Chown)
            .RunWithMounts(
                "composer install --no-dev --no-interaction --no-progress --prefer-dist --no-scripts --no-autoloader",
                ComposerCacheMount)
            .EmptyLine();
    }

    private static string Chown => $"{PhpImages.ContainerUser}:{PhpImages.ContainerUser}";

    /// <summary>
    /// Rejects values that cannot be safely written into a shell command in a generated Dockerfile.
    /// </summary>
    private static void ValidateShellToken(string value, string description, string resourceName)
    {
        ValidateIniValue(value, description, resourceName);

        // Extension names reach a RUN command unquoted, so anything outside this set could inject a command.
        foreach (var character in value)
        {
            if (!char.IsAsciiLetterOrDigit(character) && character is not ('-' or '_' or '.'))
            {
                throw new DistributedApplicationException(
                    $"The PHP app '{resourceName}' has a {description} of '{value}', which contains the character " +
                    $"'{character}'. Only letters, digits, hyphen, underscore and dot are allowed.");
            }
        }
    }

    /// <summary>
    /// Escapes a value for a double-quoted php.ini entry.
    /// </summary>
    /// <remarks>
    /// A double quote would end the value early. Backslashes are left alone: php.ini does not treat them as
    /// escapes, and rewriting them would corrupt Windows-style paths and regular expressions.
    /// </remarks>
    private static string EscapeIniValue(string value) => value.Replace("\"", "\\\"");

    private static void ValidateIniValue(string value, string description, string resourceName)
    {
        if (string.IsNullOrWhiteSpace(value))
        {
            throw new DistributedApplicationException(
                $"The PHP app '{resourceName}' has an empty {description}.");
        }

        foreach (var character in value)
        {
            if (char.IsControl(character))
            {
                throw new DistributedApplicationException(
                    $"The PHP app '{resourceName}' has a {description} containing the control character " +
                    $"U+{(int)character:X4}. Control characters cannot be written to a generated Dockerfile.");
            }
        }
    }

    /// <summary>
    /// Wraps a value in single quotes for the shell form of RUN, leaving already-safe tokens bare.
    /// </summary>
    private static string ShellQuote(string value)
    {
        if (value.Length > 0 && value.All(static c => char.IsAsciiLetterOrDigit(c) || c is '-' or '_' or '.' or '/' or '=' or ',' or ':'))
        {
            return value;
        }

        // An embedded single quote closes the run, escapes itself, and reopens: don't => 'don'\''t'.
        return $"'{value.Replace("'", "'\\''")}'";
    }
}

#pragma warning restore ASPIREDOCKERFILEBUILDER001
