#pragma warning disable ASPIREDOCKERFILEBUILDER001

using Aspire.Hosting.ApplicationModel;
using Aspire.Hosting.ApplicationModel.Docker;

namespace Aspire.Hosting.PHP;

/// <summary>
/// Writes the Dockerfiles this integration generates.
/// </summary>
/// <remarks>
/// <para>
/// PHP images are single stage, unlike the Rust and Python ones. There is nothing to compile away: the source
/// that runs is the source that shipped, and the base images already contain Composer, so a separate runtime
/// stage would be byte-identical to the build stage. Layer caching is still handled properly by copying
/// <c>composer.json</c> ahead of the rest of the source.
/// </para>
/// <para>
/// Two shapes are produced. <see cref="WritePublishDockerfile"/> builds the deployable image with the source
/// baked in. <see cref="WriteDevDockerfile"/> builds only the environment — extensions and ini settings — for
/// run mode, where the source arrives through a bind mount instead.
/// </para>
/// </remarks>
internal static class PhpDockerfileGenerator
{
    private const string ComposerCacheMount = "type=cache,target=/tmp/composer-cache";

    /// <summary>
    /// Files excluded from the build context when the application has no <c>.dockerignore</c> of its own.
    /// </summary>
    /// <remarks>
    /// <c>vendor</c> matters most: it is routinely hundreds of megabytes, it is rebuilt inside the image anyway,
    /// and a host <c>vendor</c> built on Windows or macOS can carry platform-specific paths into a Linux image.
    /// </remarks>
    public const string DefaultBuildContextIgnoreContent = """
        # Generated by Aspire.Hosting.PHP. Author <contextRoot>/.dockerignore to take over these rules.
        vendor
        node_modules
        .git
        .gitignore
        .env
        .env.*
        .aspire
        aspire-output
        .DS_Store
        Dockerfile
        Dockerfile.*
        .dockerignore

        """;

    /// <summary>
    /// Writes the image that runs the application, with the source baked in.
    /// </summary>
    public static void WritePublishDockerfile(IPhpResource resource, DockerfileBuilderCallbackContext context)
    {
        var options = PhpDockerfileOptions.Resolve(resource, context.Resource);

        var stage = context.Builder.From(options.Image);

        WriteEnvironmentSetup(stage, options, resource.Name);

        stage
            .WorkDir(PhpImages.AppBaseDirectory)
            .EmptyLine();

        WriteComposerInstall(stage, options);

        stage
            .Comment("Application source")
            .Copy(".", ".", Chown)
            .EmptyLine();

        if (options.UsesComposer)
        {
            // Deferred until the full source is present: the autoloader classmap has to see every class, and
            // scripts such as post-install-cmd routinely touch files that only exist in the complete tree.
            stage
                .Comment("Build the optimized autoloader now the whole source tree is present")
                .RunWithMounts("composer dump-autoload --optimize --no-dev --no-interaction", ComposerCacheMount)
                .EmptyLine();
        }

        if (options.IsWeb)
        {
            // No ENTRYPOINT: the base image starts FrankenPHP itself. The listening port and document root are
            // supplied as resource environment variables so Aspire can resolve the port it allocated.
            stage
                .Comment("FrankenPHP serves the application; the port and document root arrive as environment variables")
                .Expose(PhpImages.DefaultWebContainerPort);
        }
        else
        {
            stage.Entrypoint(["php", options.ScriptPath ?? throw new DistributedApplicationException(
                $"The PHP app '{resource.Name}' has no script to run. This is a bug in Aspire.Hosting.PHP.")]);
        }
    }

    /// <summary>
    /// Writes the run-mode image: the PHP environment only, with no application source.
    /// </summary>
    /// <remarks>
    /// The source is bind-mounted at run time instead of copied, so edits take effect without a rebuild and
    /// <c>vendor/</c> is written back to the host where editors and static analysis can see it.
    /// </remarks>
    public static void WriteDevDockerfile(IPhpResource resource, DockerfileBuilderCallbackContext context)
    {
        var options = PhpDockerfileOptions.Resolve(resource, context.Resource);

        var stage = context.Builder.From(options.Image);

        stage
            .Comment("Run-mode image: environment only. The application is bind-mounted at " + PhpImages.AppBaseDirectory + ".")
            .EmptyLine();

        WriteEnvironmentSetup(stage, options, resource.Name);

        stage.WorkDir(PhpImages.AppBaseDirectory);
    }

    private static void WriteEnvironmentSetup(DockerfileStage stage, PhpDockerfileOptions options, string resourceName)
    {
        var needsRoot = options.Extensions.Count > 0 || options.IniSettings.Count > 0;
        if (!needsRoot)
        {
            return;
        }

        // install-php-extensions and writing into conf.d both need root; the images otherwise run unprivileged.
        stage.User("root");

        if (options.Extensions.Count > 0)
        {
            foreach (var extension in options.Extensions)
            {
                ValidateShellToken(extension, "PHP extension name", resourceName);
            }

            stage
                .Comment("PHP extensions")
                .Run($"install-php-extensions {string.Join(" ", options.Extensions)}")
                .EmptyLine();
        }

        if (options.IniSettings.Count > 0)
        {
            foreach (var setting in options.IniSettings)
            {
                ValidateIniValue(setting.Key, "php.ini setting name", resourceName);
                ValidateIniValue(setting.Value, $"php.ini value for '{setting.Key}'", resourceName);
            }

            // printf with a %s per line rather than echo: echo's handling of backslashes and leading dashes
            // differs between shells, and these values come from the caller.
            var format = string.Join("", Enumerable.Repeat("%s\\n", options.IniSettings.Count));
            var arguments = string.Join(
                " ",
                options.IniSettings.Select(setting => ShellQuote($"{setting.Key}={setting.Value}")));

            stage
                .Comment("php.ini settings. The four z prefix sorts after the base image's own ini files.")
                .Run($"printf '{format}' {arguments} > {PhpImages.PhpConfDirectory}/{PhpImages.GeneratedIniFileName}")
                .EmptyLine();
        }

        stage
            .User(PhpImages.ContainerUser)
            .EmptyLine();
    }

    private static void WriteComposerInstall(DockerfileStage stage, PhpDockerfileOptions options)
    {
        if (!options.UsesComposer)
        {
            return;
        }

        // Copied ahead of the source so a source-only edit does not invalidate the dependency layer.
        // composer.lock is matched by a glob rather than named, because COPY fails outright on a missing
        // file and an application without a committed lock file is legal.
        stage
            .Comment("Dependencies first, so editing source does not reinstall them")
            .Copy("composer.json composer.lock*", "./", Chown)
            .RunWithMounts(
                "composer install --no-dev --no-interaction --no-progress --prefer-dist --no-scripts --no-autoloader",
                ComposerCacheMount)
            .EmptyLine();
    }

    private static string Chown => $"{PhpImages.ContainerUser}:{PhpImages.ContainerUser}";

    /// <summary>
    /// Rejects values that cannot be safely written into a shell command in a generated Dockerfile.
    /// </summary>
    private static void ValidateShellToken(string value, string description, string resourceName)
    {
        ValidateIniValue(value, description, resourceName);

        // Extension names reach a RUN command unquoted, so anything outside this set could inject a command.
        foreach (var character in value)
        {
            if (!char.IsAsciiLetterOrDigit(character) && character is not ('-' or '_' or '.'))
            {
                throw new DistributedApplicationException(
                    $"The PHP app '{resourceName}' has a {description} of '{value}', which contains the character " +
                    $"'{character}'. Only letters, digits, hyphen, underscore and dot are allowed.");
            }
        }
    }

    private static void ValidateIniValue(string value, string description, string resourceName)
    {
        if (string.IsNullOrWhiteSpace(value))
        {
            throw new DistributedApplicationException(
                $"The PHP app '{resourceName}' has an empty {description}.");
        }

        foreach (var character in value)
        {
            if (char.IsControl(character))
            {
                throw new DistributedApplicationException(
                    $"The PHP app '{resourceName}' has a {description} containing the control character " +
                    $"U+{(int)character:X4}. Control characters cannot be written to a generated Dockerfile.");
            }
        }
    }

    /// <summary>
    /// Wraps a value in single quotes for the shell form of RUN, leaving already-safe tokens bare.
    /// </summary>
    private static string ShellQuote(string value)
    {
        if (value.Length > 0 && value.All(static c => char.IsAsciiLetterOrDigit(c) || c is '-' or '_' or '.' or '/' or '=' or ',' or ':'))
        {
            return value;
        }

        // An embedded single quote closes the run, escapes itself, and reopens: don't => 'don'\''t'.
        return $"'{value.Replace("'", "'\\''")}'";
    }
}

#pragma warning restore ASPIREDOCKERFILEBUILDER001
