using System.Text;

namespace Aspire.Hosting.PHP;

/// <summary>
/// Writes the OpenTelemetry Collector configuration.
/// </summary>
/// <remarks>
/// Every value that is not known at build time is written as a <c>${env:NAME}</c> reference, which the
/// collector expands at startup. That keeps the Application Insights connection string — which is a secret —
/// out of the generated file and out of anything that file is copied into.
/// </remarks>
internal static class PhpTelemetryCollectorConfig
{
    /// <summary>Environment variable carrying the Aspire dashboard's OTLP endpoint.</summary>
    public const string DashboardEndpointVariable = "ASPIRE_OTLP_ENDPOINT";

    /// <summary>Environment variable carrying the Application Insights connection string.</summary>
    public const string ApplicationInsightsVariable = "APPLICATIONINSIGHTS_CONNECTION_STRING";

    /// <summary>Environment variable carrying the dashboard's OTLP API key.</summary>
    /// <remarks>
    /// The dashboard rejects unauthenticated OTLP with a 401 that names no cause, so this is easy to miss:
    /// the collector receives spans happily and then silently drops them on the way out.
    /// </remarks>
    public const string DashboardApiKeyVariable = "ASPIRE_OTLP_API_KEY";

    /// <summary>Port the collector receives OTLP over HTTP on.</summary>
    public const int HttpPort = 4318;

    /// <summary>Port the collector receives OTLP over gRPC on.</summary>
    public const int GrpcPort = 4317;

    /// <summary>
    /// Builds the collector configuration.
    /// </summary>
    /// <param name="forwardToDashboard">Forward everything to the Aspire dashboard as well.</param>
    /// <param name="forwardToApplicationInsights">Forward everything to Application Insights as well.</param>
    /// <param name="skipTlsVerification">
    /// Skip certificate verification on the dashboard exporter. True while running, where the dashboard uses a
    /// development certificate the collector has no reason to trust.
    /// </param>
    /// <param name="dashboardNeedsApiKey">
    /// Send the dashboard's OTLP API key. Without it the dashboard answers 401 and the collector drops
    /// everything it forwards.
    /// </param>
    public static string Build(
        bool forwardToDashboard,
        bool forwardToApplicationInsights,
        bool skipTlsVerification,
        bool dashboardNeedsApiKey)
    {
        var exporters = new List<string>();
        var builder = new StringBuilder();

        builder.AppendLine("# Generated by Aspire.Hosting.PHP. Edits are overwritten on the next run.");
        builder.AppendLine("receivers:");
        builder.AppendLine("  otlp:");
        builder.AppendLine("    protocols:");
        builder.AppendLine("      http:");
        builder.AppendLine($"        endpoint: 0.0.0.0:{HttpPort}");
        builder.AppendLine("      grpc:");
        builder.AppendLine($"        endpoint: 0.0.0.0:{GrpcPort}");
        builder.AppendLine();

        builder.AppendLine("processors:");

        // The whole point of the collector for PHP: it batches on its own schedule, so the PHP process does
        // not have to hold a request open while telemetry is shipped.
        builder.AppendLine("  batch:");
        builder.AppendLine("    timeout: 5s");
        builder.AppendLine("    send_batch_size: 512");
        builder.AppendLine();

        builder.AppendLine("exporters:");

        if (forwardToDashboard)
        {
            exporters.Add("otlphttp/dashboard");
            builder.AppendLine("  otlphttp/dashboard:");
            builder.AppendLine($"    endpoint: ${{env:{DashboardEndpointVariable}}}");

            // The collector compresses with gzip by default, and the dashboard's OTLP/HTTP endpoint parses the
            // body as protobuf without decompressing it. The symptom is a 500 and an
            // InvalidProtocolBufferException about an invalid wire type, which points nowhere near compression.
            builder.AppendLine("    compression: none");

            if (dashboardNeedsApiKey)
            {
                builder.AppendLine("    headers:");
                builder.AppendLine($"      x-otlp-api-key: ${{env:{DashboardApiKeyVariable}}}");
            }

            if (skipTlsVerification)
            {
                // The dashboard presents a development certificate. Verifying it would mean teaching the
                // collector about the local certificate authority for no benefit on loopback traffic.
                builder.AppendLine("    tls:");
                builder.AppendLine("      insecure_skip_verify: true");
            }

            builder.AppendLine();
        }

        if (forwardToApplicationInsights)
        {
            exporters.Add("azuremonitor");
            builder.AppendLine("  azuremonitor:");
            builder.AppendLine($"    connection_string: ${{env:{ApplicationInsightsVariable}}}");
            builder.AppendLine();
        }

        if (exporters.Count == 0)
        {
            // A pipeline with no exporters is a configuration error the collector refuses to start with, so
            // there is always at least one. debug also makes "did anything arrive?" answerable from the logs.
            exporters.Add("debug");
            builder.AppendLine("  debug:");
            builder.AppendLine("    verbosity: normal");
            builder.AppendLine();
        }

        var exporterList = string.Join(", ", exporters);

        builder.AppendLine("service:");
        builder.AppendLine("  telemetry:");
        builder.AppendLine("    logs:");
        builder.AppendLine("      level: info");
        builder.AppendLine("  pipelines:");

        // Traces, metrics and logs all go the same way. PHP applications that emit logs through the SDK are
        // rare, but a pipeline that is configured and unused costs nothing.
        foreach (var signal in (string[])["traces", "metrics", "logs"])
        {
            builder.AppendLine($"    {signal}:");
            builder.AppendLine("      receivers: [otlp]");
            builder.AppendLine("      processors: [batch]");
            builder.AppendLine($"      exporters: [{exporterList}]");
        }

        return builder.ToString();
    }
}
